FROM ubuntu:16.04

ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV DEBIAN_FRONTEND noninteractive
ENV BASH_ENV /etc/profile
SHELL ["/bin/bash", "-c"]

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y \
        --no-install-recommends \
        build-essential \
        unzip \
        file \
        git \
        ca-certificates \
        rsync && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY _deps/bazel-0.11.0-installer-linux-x86_64.sh .
RUN bash bazel-0.11.0-installer-linux-x86_64.sh --prefix=/opt/bazel-0.11.0 && \
    echo 'export PATH=$PATH:/opt/bazel-0.11.0/bin' > /etc/profile.d/bazel.sh && \
    rm bazel-0.11.0-installer-linux-x86_64.sh

COPY _deps/Miniconda3-4.5.1-Linux-x86_64.sh .
RUN bash Miniconda3-4.5.1-Linux-x86_64.sh -b -f -p /opt/conda && \
    echo 'export PATH=$PATH:/opt/conda/bin' > /etc/profile.d/conda.sh && \
    /opt/conda/bin/conda update -q -y -n base conda && \
    /opt/conda/bin/conda install -q -y numpy && \
    rm Miniconda3-4.5.1-Linux-x86_64.sh

RUN useradd -m tensorflow && \
    passwd -d tensorflow

USER tensorflow
WORKDIR /home/tensorflow

CMD ["/bin/bash"]
